name: gitops-diff

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    # Folder where we keep app config, e.g. helm values
    - 'apps/**'

jobs:
  hydrate-manifests:
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
    runs-on:
    - ubuntu-latest

    permissions:
      id-token: write
      pull-requests: write
      contents: read

    strategy:
      matrix:
        ref: [head,base]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Checkout head and base of a PR in parallel
        ref: ${{ matrix.ref == 'head' && github.event.pull_request.head.ref || github.event.pull_request.base.ref }}
        fetch-depth: 2

    # Login to GCP with WIF for using Artifact Registry for private Helm charts
    - name: Login to Google Cloud Platform
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/<PROJET_ID>/locations/global/workloadIdentityPools/github/providers/<ORG>

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'

    - name: Setup Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: '3.17.0'

    - name: Register gcloud as credential helper
      run: gcloud auth configure-docker europe-west2-docker.pkg.dev

    # Generate all ArgoCD app CRDs into a single manifest
    - name: Generate ArgoCD Application manifests
      run: |
        mkdir manifests
        helm template -s templates/application.yaml . > manifests/applications.yaml

    # Use github cache action to download cached Helm chart archives
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v4
      with:
        path: charts
        key: ${{ github.repository }}/charts-${{ hashFiles('charts/**/Chart.yaml') }}
        restore-keys: |
          ${{ github.repository }}/charts-

    - name: Setup ArgoCD Hydrate
      uses: kazysgurskas/setup-argocd-hydrate@v1.0.0

    - name: Run ArgoCD Hydrate
      run: argocd-hydrate

    - name: Upload manifests as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.ref }}-manifests
        path: manifests/
        retention-days: 1

  generate-diff:
    needs: hydrate-manifests
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
    runs-on:
    - fireactions-c2-m4

    steps:
    - name: Download head manifests
      uses: actions/download-artifact@v4
      with:
        name: head-manifests
        path: head

    - name: Download base manifests
      uses: actions/download-artifact@v4
      with:
        name: base-manifests
        path: base

    - name: Post diff
      uses: kazysgurskas/diff-action@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source-dir: base
        target-dir: head
